# ===============================
# Только секреты (всё остальное — в config-server/configs/auth-service.yml)
# ===============================
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET}
spring.mail.password=${MAILTRAP_PASSWORD}
