# Общие дефолты для ВСЕХ сервисов (перекрываются {service-name}.yml)
spring:
  jpa:
    open-in-view: false
  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: health, info
